[TASK] Allow other branches and remotes

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,6 +1,6 @@
 #!/usr/bin/env sh
 #
-# Install or update phpMyAdmin
+# Setup phpMyAdmin
 # Copyright (C) 2019  Gilbertsoft
 #
 # This program is free software: you can redistribute it and/or modify
@@ -16,15 +16,21 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+# Search for an existing www directory
+if [ ! -d "www" ]; then
+    echo "Error web directory 'www' was not found!"
+    exit 1
+fi
+
 # Create configuration from dist
 if [ ! -f "config.inc.php" ]; then
     cp config.dist.inc.php config.inc.php
     sed -i -e "s/add_new_secret_here/`pwgen -s 32 1`/g" config.inc.php
 fi
 
-# Install or update phpMyAdmin from github
+# Install or update phpMyAdmin
 if [ ! -d "www/.git" ]; then
-    # Install stable version to www-new
+    # Clone stable version from github to www-new
     git clone -q --depth=1 --branch=STABLE https://github.com/phpmyadmin/phpmyadmin.git www-new
 
     # Symlink configuration
@@ -36,10 +42,19 @@ if [ ! -d "www/.git" ]; then
     # Go live
     mv www-new www
 else
-    # Update stable version
-    cd www
-    git pull -q origin STABLE
-    cd ..
+    # Change to web directory
+    pushd www
+
+    if [ "$1" = "init" ]; then
+        # Reset to STABLE and update
+        git reset -q --hard origin/STABLE
+        git pull -q origin STABLE
+    else
+        # Update current branch
+        git pull -q
+    fi
+
+    popd
 fi
 
 # Register cron job
@@ -48,4 +63,5 @@ if [ ! -f ".jobregistered" ]; then
     touch .jobregistered
 fi
 
+echo ""
 echo "phpMyAdmin is installed and up to date now!"
